FROM python:latest
RUN pip install sklearn
RUN pip install numpy
RUN pip3 install pandas
COPY fit.py .
COPY output.txt .
COPY X.txt .
COPY y.txt .
COPY mlpipeline-ui-metadata.json .
COPY roc.csv .
ENTRYPOINT fit.py
